#!/usr/bin/env python
"""Continuous multi-agent loop driver for the Kaggle competition.

Stage machine:  scout (time-triggered, 24h) -> research -> implement -> submit -> review -> research ...

Each stage runs as an isolated headless Claude Code session (`claude -p --agent <name>`),
so context never accumulates across stages and any stage can be retried on its own.
All durable state lives in `orchestrator/state.json`, which makes the loop crash-safe
and resumable after a usage-limit block (see the `/continue` command).
"""
from __future__ import annotations

import argparse
import json
import os
import re
import shutil
import subprocess
import sys
import time
from datetime import datetime, timedelta, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ORCH = ROOT / "orchestrator"
SHARED = ROOT / "shared_memory"
CONFIG_PATH = ORCH / "config.json"
STATE_PATH = ORCH / "state.json"
LOG_DIR = ORCH / "logs"

STAGE_ORDER = ["research", "implement", "submit", "review"]

# stage -> (file the stage must have written, section headers it must contain)
CONTRACTS = {
    "scout": ("COMPETITION.md", ["## Snapshot", "## Findings", "## Actionable"]),
    "research": ("PROPOSAL.md", ["## Hypothesis", "## Changes", "## Success criteria"]),
    "implement": (None, []),   # verified structurally in check_contract
    "submit": ("RESULTS.md", ["## Cycle"]),
    "review": ("RESULTS.md", ["### Insight"]),
}

# The submit agent classifies every run here; the orchestrator routes on it.
HANDOFF_PATH = ORCH / "handoff.json"
VALID_OUTCOMES = {"success", "dev_bug", "logic_error"}

USAGE_LIMIT_PATTERNS = [
    r"usage limit reached",
    r"claude usage limit",
    r"rate_limit_error",
    r"exceeded your.{0,30}quota",
    r"insufficient credit",
    r"credit balance is too low",
    # The CLI says "You've hit your session limit - resets 7:20pm (Asia/Bangkok)".
    # Without this the loop reads a quota block as a code failure and burns all
    # three retries in seconds instead of parking with the reset time. Kept
    # narrow on purpose: `blob` includes the agents' own text, and a bare
    # "session limit" would let an agent discussing submission caps park the loop.
    r"hit your .{0,30}limit",
]
# "at" is optional: the CLI writes "resets 7:20pm (Asia/Bangkok)" with no "at".
RESET_TIME_PATTERN = re.compile(
    r"reset(?:s|ting)?\s+(?:at\s+)?([0-9]{1,2}(?::[0-9]{2})?\s*(?:am|pm)?[^\n.]*)", re.I
)


# --------------------------------------------------------------------------- io
def now():
    return datetime.now(timezone.utc)


def iso(dt):
    return dt.astimezone(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def parse_iso(s):
    if not s:
        return None
    try:
        return datetime.strptime(s, "%Y-%m-%dT%H:%M:%SZ").replace(tzinfo=timezone.utc)
    except ValueError:
        return None


def load_config():
    return json.loads(CONFIG_PATH.read_text(encoding="utf-8"))


DEFAULT_STATE = {
    "cycle": 0,
    "stage": "research",
    "status": "pending",          # pending | running | done | blocked | failed
    "blocked_reason": None,
    "resume_after": None,
    "last_scout_at": None,
    "consecutive_failures": 0,
    "repair_attempts": 0,         # implement<->submit fix rounds in this cycle
    "replan_attempts": 0,         # research re-plans triggered by a logic error
    "last_failure": None,         # {"outcome","reason","exp","stage"} for the retry prompt
    "submissions": [],            # [{"at": iso, "cycle": n, "lb": float|None}]
    "best": {"cycle": None, "cv": None, "lb": None},
    "history": [],
}


def load_state():
    if STATE_PATH.exists():
        st = json.loads(STATE_PATH.read_text(encoding="utf-8"))
        return {**DEFAULT_STATE, **st}
    return dict(DEFAULT_STATE)


def save_state(st):
    STATE_PATH.write_text(json.dumps(st, indent=2), encoding="utf-8")
    _mirror_state_markdown(st)


def _mirror_state_markdown(st):
    """Human-readable mirror of state.json, kept inside shared memory."""
    best = st.get("best") or {}
    lines = [
        "# Loop state",
        "",
        "_Auto-generated by `orchestrator/run_loop.py` at " + iso(now()) + ". Do not edit by hand._",
        "",
        "- **Cycle**: {}".format(st["cycle"]),
        "- **Stage**: `{}`".format(st["stage"]),
        "- **Status**: `{}`".format(st["status"]),
        "- **Blocked reason**: {}".format(st.get("blocked_reason") or "-"),
        "- **Repair attempts (this cycle)**: {}".format(st.get("repair_attempts", 0)),
        "- **Replans (this cycle)**: {}".format(st.get("replan_attempts", 0)),
        "- **Last scout**: {}".format(st.get("last_scout_at") or "never"),
        "- **Submissions in last 24h**: {}".format(submissions_today(st)),
        "- **Best so far**: cycle {} | CV {} | LB {}".format(
            best.get("cycle"), best.get("cv"), best.get("lb")
        ),
        "",
        "## Recent history",
        "",
        "| when | cycle | stage | outcome |",
        "| --- | --- | --- | --- |",
    ]
    for h in st.get("history", [])[-15:]:
        lines.append(
            "| {} | {} | {} | {} |".format(
                h.get("at"), h.get("cycle"), h.get("stage"), h.get("outcome")
            )
        )
    (SHARED / "STATE.md").write_text("\n".join(lines) + "\n", encoding="utf-8")


def log(msg):
    print("[{}] {}".format(iso(now()), msg), flush=True)


# ------------------------------------------------------------------- quota/gate
def submissions_today(st):
    cutoff = now() - timedelta(hours=24)
    return sum(1 for s in st.get("submissions", []) if (parse_iso(s.get("at")) or cutoff) > cutoff)


def submit_slots_left(st, cfg):
    cap = cfg["competition"]["max_daily_submissions"]
    reserve = cfg["loop"]["submit_gate"].get("reserve_daily_slots", 0)
    return max(0, cap - reserve - submissions_today(st))


# ----------------------------------------------------------------- claude shell
def claude_bin():
    exe = shutil.which("claude") or shutil.which("claude.cmd")
    if not exe:
        sys.exit("FATAL: `claude` CLI not found on PATH.")
    return exe


def build_prompt(stage, st, cfg):
    """Short kickoff prompt; the real instructions live in .claude/agents/<stage>.md."""
    common = (
        "Cycle: {}\n"
        "Shared memory folder: shared_memory/\n"
        "Competition: {} (metric: {})\n"
        "Repo: {}/{} branch {}\n"
    ).format(
        st["cycle"],
        cfg["competition"]["slug"],
        cfg["competition"]["metric"],
        cfg["github"]["owner"],
        cfg["github"]["repo"],
        cfg["github"]["branch"],
    )
    extra = {
        "scout": "Run your scouting pass now and rewrite shared_memory/COMPETITION.md.",
        "research": (
            "Read shared_memory/COMPETITION.md and shared_memory/RESULTS.md (especially the newest "
            "### Insight block), then write this cycle's proposal to shared_memory/PROPOSAL.md."
        ),
        "implement": (
            "Read shared_memory/PROPOSAL.md and implement it. Commit and push to GitHub once the "
            "smoke test passes locally."
        ),
        "submit": (
            "Run the experiment on Kaggle and record the results. Daily submission slots left: "
            "{} of {}.".format(submit_slots_left(st, cfg), cfg["competition"]["max_daily_submissions"])
        ),
        "review": (
            "Read shared_memory/PROPOSAL.md and the newest cycle block in shared_memory/RESULTS.md, "
            "then append this cycle's ### Insight section."
        ),
    }[stage]

    # A bounced run must tell the next stage exactly what it is fixing, or the
    # retry just reproduces the same failure.
    fail = st.get("last_failure")
    if fail and stage in ("implement", "research"):
        rcfg = cfg["loop"].get("repair", {})
        extra += (
            "\n\n--- THIS IS A RETRY ---\n"
            "The previous run of this proposal produced no usable score.\n"
            "The submit agent classified it as: {}\n"
            "Reason: {}\n".format(fail.get("outcome"), fail.get("reason"))
        )
        if fail.get("details"):
            extra += "Details: {}\n".format(fail["details"])
        if stage == "implement":
            extra += (
                "Repair attempt {} of {}. Fix that specific defect: do not restart the "
                "proposal, do not change the primary variable, and re-run the smoke test "
                "before pushing. The failing run is recorded in the newest cycle block of "
                "shared_memory/RESULTS.md.".format(
                    st.get("repair_attempts", 0), rcfg.get("max_repair_attempts", 3))
            )
        else:
            extra += (
                "Replan {} of {}. The code was implemented as written and the idea itself "
                "did not survive contact with the data, so propose something different. "
                "State explicitly in ## Rationale what the previous attempt ruled out.".format(
                    st.get("replan_attempts", 0), rcfg.get("max_replans_per_cycle", 2))
            )
    return common + "\n" + extra


def run_stage(stage, st, cfg, dry_run=False):
    """Execute one stage. Returns (outcome, detail); outcome is done|blocked|failed."""
    acfg = cfg["agents"][stage]
    cycle_log_dir = LOG_DIR / "cycle-{:04d}".format(st["cycle"])
    cycle_log_dir.mkdir(parents=True, exist_ok=True)
    log_path = cycle_log_dir / (stage + ".jsonl")

    cmd = [
        claude_bin(),
        "-p", build_prompt(stage, st, cfg),
        "--agent", stage,
        "--model", acfg["model"],
        "--effort", acfg.get("effort", "medium"),
        "--permission-mode", cfg["claude"]["permission_mode"],
        "--output-format", "stream-json",
        "--verbose",
    ] + list(cfg["claude"].get("extra_args", []))

    if dry_run:
        log("DRY-RUN stage={} model={} effort={} -> {}".format(
            stage, acfg["model"], acfg.get("effort"), log_path))
        if stage == "submit":
            # stand in for the agent's verdict so routing is exercised end to end;
            # override with DRY_RUN_OUTCOME=dev_bug|logic_error to test the repair paths
            outcome = os.environ.get("DRY_RUN_OUTCOME", "success")
            HANDOFF_PATH.write_text(json.dumps({
                "outcome": outcome,
                "reason": "" if outcome == "success" else "dry-run simulated " + outcome,
                "exp": "exp_{:04d}".format(st["cycle"]),
            }, indent=2), encoding="utf-8")
        return "done", "dry-run"

    log("--> stage={} cycle={} model={} effort={}".format(
        stage, st["cycle"], acfg["model"], acfg.get("effort")))
    started = time.time()
    tail = []
    plain_tail = []
    result_text = ""
    is_error = False

    env = dict(os.environ)
    env["CLAUDE_LOOP_CYCLE"] = str(st["cycle"])
    env["CLAUDE_LOOP_STAGE"] = stage

    try:
        proc = subprocess.Popen(
            cmd, cwd=str(ROOT),
            # DEVNULL, not inherit: `claude -p` otherwise waits 3s for stdin per stage.
            stdin=subprocess.DEVNULL,
            # stderr merged in on purpose - usage-limit notices arrive on stderr and
            # the detector below needs to see them. Non-JSON lines are skipped.
            stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
            text=True, encoding="utf-8", errors="replace", bufsize=1, env=env,
        )
    except OSError as e:
        return "failed", "could not launch claude: {}".format(e)

    timeout = cfg["loop"]["stage_timeout_seconds"]
    timed_out = False
    with log_path.open("a", encoding="utf-8") as lf:
        for line in proc.stdout:
            lf.write(line)
            tail.append(line)
            if len(tail) > 400:
                tail.pop(0)
            try:
                evt = json.loads(line)
            except json.JSONDecodeError:
                evt = None
                # Non-JSON lines are the CLI's own notices (stderr is merged in).
                # The quota check reads only these, never the agent's stream-json,
                # so an agent quoting a limit message cannot park the loop.
                plain_tail.append(line)
                if len(plain_tail) > 200:
                    plain_tail.pop(0)
            if isinstance(evt, dict):
                et = evt.get("type")
                if et == "assistant":
                    for blk in evt.get("message", {}).get("content", []):
                        if blk.get("type") == "tool_use":
                            log("    . {}".format(blk.get("name")))
                        elif blk.get("type") == "text" and blk.get("text", "").strip():
                            log("    > {}".format(blk["text"].strip().splitlines()[0][:140]))
                elif et == "result":
                    result_text = evt.get("result", "") or ""
                    is_error = bool(evt.get("is_error"))
            if time.time() - started > timeout:
                proc.kill()
                timed_out = True
                break
        proc.wait()

    if timed_out:
        return "failed", "stage exceeded timeout of {}s".format(timeout)

    # A real quota block always fails the process, so the text is only consulted
    # on a failed run. A stage that exits 0 has done its job, whatever it wrote.
    if proc.returncode != 0 or is_error:
        raw = "".join(plain_tail) + chr(10) + result_text
        blob = raw.lower()
        for pat in USAGE_LIMIT_PATTERNS:
            if re.search(pat, blob):
                m = RESET_TIME_PATTERN.search(raw)
                suffix = " (resets {})".format(m.group(1).strip()) if m else ""
                return "blocked", "usage limit hit" + suffix
        return "failed", "exit={} is_error={} :: {}".format(
            proc.returncode, is_error, result_text[:400])

    ok, why = check_contract(stage)
    if not ok:
        return "failed", "output contract not satisfied: " + why

    log("<-- stage={} done in {}s".format(stage, int(time.time() - started)))
    return "done", result_text[:400]


def check_contract(stage):
    fname, sections = CONTRACTS.get(stage, (None, []))
    if fname:
        path = SHARED / fname
        if not path.exists():
            return False, "{} was not created".format(fname)
        text = path.read_text(encoding="utf-8", errors="replace")
        missing = [s for s in sections if s not in text]
        if missing:
            return False, "{} missing sections: {}".format(fname, missing)
    if stage == "implement":
        # Without this a no-op run passes as success and submit burns a Kaggle
        # kernel on a commit that has no pipeline code in it.
        entry = ROOT / "src" / "run.py"
        if not entry.exists():
            return False, ("src/run.py does not exist - the stage reported success "
                           "without leaving an entrypoint the Kaggle notebook can call")

    if stage == "submit":
        _, ok, why = read_handoff()
        if not ok:
            return False, why
    return True, ""


def read_handoff():
    """(handoff dict, valid?, why-not) - the submit agent's verdict on the run."""
    if not HANDOFF_PATH.exists():
        return {}, False, ("orchestrator/handoff.json was not written; the submit agent "
                           "must classify every run as success / dev_bug / logic_error")
    try:
        h = json.loads(HANDOFF_PATH.read_text(encoding="utf-8"))
    except json.JSONDecodeError as e:
        return {}, False, "handoff.json is not valid JSON: {}".format(e)
    outcome = h.get("outcome")
    if outcome not in VALID_OUTCOMES:
        return h, False, "handoff.json outcome {!r} not one of {}".format(
            outcome, sorted(VALID_OUTCOMES))
    if outcome != "success" and not str(h.get("reason", "")).strip():
        return h, False, "handoff.json outcome {!r} needs a non-empty reason".format(outcome)
    return h, True, ""


def clear_handoff():
    """Consume the verdict so a stale file can never route the next run."""
    if HANDOFF_PATH.exists():
        HANDOFF_PATH.unlink()


# ----------------------------------------------------------------------- driver
def due_for_scout(st, cfg):
    last = parse_iso(st.get("last_scout_at"))
    if last is None:
        return True
    return now() - last >= timedelta(hours=cfg["loop"]["scout_interval_hours"])


def record(st, stage, outcome, detail=""):
    st["history"].append({
        "at": iso(now()), "cycle": st["cycle"], "stage": stage,
        "outcome": outcome, "detail": detail[:300],
    })
    st["history"] = st["history"][-200:]


def advance(st):
    """Move to the next stage, rolling the cycle counter over after review."""
    idx = STAGE_ORDER.index(st["stage"])
    if idx == len(STAGE_ORDER) - 1:
        st["cycle"] += 1
        st["stage"] = STAGE_ORDER[0]
        st["repair_attempts"] = 0
        st["replan_attempts"] = 0
    else:
        st["stage"] = STAGE_ORDER[idx + 1]
    st["status"] = "pending"


def route_after_submit(st, cfg):
    """Decide where a finished run goes next, from the submit agent's verdict.

    A run that produced no usable score is not a cycle - it is a defect, and the
    defect has two very different causes:

      dev_bug     something we wrote is broken (crash, bad submission format,
                  overlapping masks). The proposal is still fine, so go straight
                  back to implement and fix it.
      logic_error the code did what it was told and the idea itself did not hold
                  up (unrunnable plan, wrong data assumption). Code cannot fix
                  that, so go back to research for a new proposal.

    implement <-> submit keeps cycling until a run scores, bounded so a loop that
    cannot fix itself escalates instead of burning cycles forever.
    """
    h, ok, why = read_handoff()
    rcfg = cfg["loop"].get("repair", {})
    max_repair = rcfg.get("max_repair_attempts", 3)
    max_replan = rcfg.get("max_replans_per_cycle", 2)

    if not ok:                       # contract check already failed on this
        return "failed", why
    outcome = h["outcome"]
    reason = str(h.get("reason", "")).strip()
    st["last_failure"] = None if outcome == "success" else {
        "outcome": outcome,
        "reason": reason,
        "exp": h.get("exp"),
        "details": h.get("details"),
        "at": iso(now()),
    }
    clear_handoff()

    if outcome == "success":
        st["repair_attempts"] = 0
        st["replan_attempts"] = 0
        advance(st)                  # -> review
        return "success", "run scored; handing to review"

    if outcome == "dev_bug":
        st["repair_attempts"] += 1
        if st["repair_attempts"] <= max_repair:
            st["stage"] = "implement"
            st["status"] = "pending"
            return "repair", "dev_bug #{}/{}: {}".format(
                st["repair_attempts"], max_repair, reason)
        # implement cannot fix it - treat as a planning problem instead
        log("{} repair attempts exhausted; escalating to research".format(max_repair))
        outcome, reason = "logic_error", (
            "escalated after {} failed repairs :: {}".format(max_repair, reason))

    if outcome == "logic_error":
        st["replan_attempts"] += 1
        st["repair_attempts"] = 0
        if st["replan_attempts"] <= max_replan:
            st["cycle"] += 1         # a new proposal is a new cycle
            st["stage"] = "research"
            st["status"] = "pending"
            return "replan", "logic_error #{}/{}: {}".format(
                st["replan_attempts"], max_replan, reason)
        return "exhausted", (
            "{} replans and {} repairs did not produce a scoring run :: {}".format(
                max_replan, max_repair, reason))

    return "failed", "unhandled outcome {!r}".format(outcome)


def main():
    ap = argparse.ArgumentParser(description="Continuous Kaggle agent loop")
    ap.add_argument("--resume", action="store_true",
                    help="clear a blocked status and continue from the saved stage")
    ap.add_argument("--once", action="store_true", help="run a single stage then exit")
    ap.add_argument("--stage", choices=STAGE_ORDER + ["scout"], help="force the next stage")
    ap.add_argument("--cycles", type=int, default=0, help="stop after N cycles (0 = unlimited)")
    ap.add_argument("--dry-run", action="store_true", help="show what would run, call nothing")
    ap.add_argument("--status", action="store_true", help="print state and exit")
    args = ap.parse_args()

    cfg = load_config()
    st = load_state()
    LOG_DIR.mkdir(parents=True, exist_ok=True)
    SHARED.mkdir(parents=True, exist_ok=True)

    if args.status:
        print(json.dumps(st, indent=2))
        return 0

    if args.resume:
        if st["status"] == "blocked":
            log("resuming blocked stage `{}` (was: {})".format(st["stage"], st.get("blocked_reason")))
        st["status"] = "pending"
        st["blocked_reason"] = None
        st["resume_after"] = None
        st["consecutive_failures"] = 0
        # A human resume grants a fresh repair budget - correct only because the
        # human is expected to have fixed something first (see /continue).
        st["repair_attempts"] = 0
        st["replan_attempts"] = 0
    elif st["status"] == "blocked":
        log("loop is BLOCKED ({}). Run `/continue` or "
            "`python orchestrator/run_loop.py --resume`.".format(st.get("blocked_reason")))
        return 2

    if args.stage:
        st["stage"] = args.stage
    save_state(st)

    start_cycle = st["cycle"]
    limit = args.cycles or cfg["loop"].get("max_cycles", 0)

    while True:
        # 24h scout trigger, evaluated at the top of every cycle
        if st["stage"] == STAGE_ORDER[0] and due_for_scout(st, cfg):
            st["status"] = "running"
            save_state(st)
            outcome, detail = run_stage("scout", st, cfg, args.dry_run)
            record(st, "scout", outcome, detail)
            if outcome == "done":
                st["last_scout_at"] = iso(now())
            elif outcome == "blocked":
                st["status"] = "blocked"
                st["blocked_reason"] = detail
                save_state(st)
                log("BLOCKED during scout: " + detail)
                return 2
            else:
                log("scout failed ({}); continuing with the existing COMPETITION.md".format(detail))
            save_state(st)

        st["status"] = "running"
        save_state(st)
        stage = st["stage"]
        if stage == "submit":
            clear_handoff()   # never route on a previous run's verdict
        outcome, detail = run_stage(stage, st, cfg, args.dry_run)
        record(st, stage, outcome, detail)

        if outcome == "blocked":
            st["status"] = "blocked"
            st["blocked_reason"] = detail
            save_state(st)
            log("BLOCKED at stage `{}`: {}".format(stage, detail))
            log("Run `/continue` in Claude Code (or --resume) once the limit resets.")
            return 2

        if outcome == "failed":
            st["consecutive_failures"] += 1
            st["status"] = "failed"
            save_state(st)
            log("stage `{}` FAILED: {}".format(stage, detail))
            if st["consecutive_failures"] >= 3:
                st["status"] = "blocked"
                st["blocked_reason"] = "3 consecutive failures at `{}`: {}".format(stage, detail)
                save_state(st)
                log("three strikes -> parking the loop for human review.")
                return 3
            log("retrying stage `{}` (attempt {}/3)".format(stage, st["consecutive_failures"] + 1))
            continue

        st["consecutive_failures"] = 0

        if stage == "submit":
            verdict, detail = route_after_submit(st, cfg)
            record(st, "route", verdict, detail)
            log("route after submit -> {} :: {}".format(verdict, detail))
            if verdict == "exhausted":
                st["status"] = "blocked"
                st["blocked_reason"] = "repair loop exhausted: " + detail
                save_state(st)
                log("implement/submit could not produce a scoring run; "
                    "parking for human review.")
                return 3
            if verdict == "failed":
                st["status"] = "failed"
                save_state(st)
                return 3
        else:
            advance(st)
        save_state(st)

        if args.once:
            return 0
        if limit and (st["cycle"] - start_cycle) >= limit:
            log("reached cycle limit ({}); stopping.".format(limit))
            return 0
        if st["stage"] == STAGE_ORDER[0]:
            cd = cfg["loop"].get("cooldown_seconds_between_cycles", 0)
            if cd and not args.dry_run:
                log("cycle {} complete; cooling down {}s".format(st["cycle"] - 1, cd))
                time.sleep(cd)


if __name__ == "__main__":
    sys.exit(main())
